spring:
  application:
    name: social
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8000
  servlet:
    context-path: /api/v1
app:
  security:
    jwt:
      expiration: 86400000
      secret-key: d6b296e0efeb8c294a3b9ac5b6ac5e3f53a3b21347866cbb11551f87615b34382225a28e9fc146f2ddc6bae813bfa02abb607ae98189b4e84c0bf111b1a39a27
      refresh-token:
        expiration: 604800000
logging:
  level:
    org:
      springframework:
        security: DEBUG